### ISSUE TITLE
Getting "The request could not be validated"

### ISSUE THREAD

**Issue by korve** [FireController1847/Pandora.js#2]
Hey, first of all thanks for your lib! I'm trying to use it right now, but i get the following message:
`{"message":"The request could not be validated","errorCode":0,"errorString":"INVALID_REQUEST"}`

Is the lib still working with the current pandora api or is the API also geo-locked? I live in europe, maybe thats a problem?

**Comment by FireController1847** [comment]
That could be a problem but I don't believe Pandora is blocked in that region. Can you provide me with some example code or the code that you're using that caused this error?

**Comment by korve** [comment]
`await client.login(process.env.PANDORA_USER, process.env.PANDORA_PASS);`

Thats the line that throws the error.

**Comment by FireController1847** [comment]
It is possible that Pandora may have changed the requirements to their API. Unfortunately, I don't really keep an eye or on maintain this anymore, however if you're interested take a peek at the code and see if you can't fix it! :) If not, I might eventually get a chance (if GitHub will email me my notifications, and if I remember about this issue) to take a look at it and fix it.

I'll keep this issue open until the bug is properly fixed.

**Comment by korve** [comment]
I'll give it a shot :)

**Comment by FireController1847** [comment]
Hey there, I'm late in my response but unfortunately I am no longer maintaining this library. If you or anyone else would like to take a shot and continue it, feel free to fork it and let me know so I can add a link to it in the readme!
